package org.fog.test.VEC.task;

import org.fog.test.VEC.infrastructure.ComputeNode;

import java.util.concurrent.atomic.AtomicReference;

/**
 * Represents a computation task (tuple) generated by a vehicle.
 */
public class Task {

    public enum MobilityStatus { LOW, MEDIUM, HIGH }
    public enum TaskState { CREATED, QUEUED, RUNNING, COMPLETED, FAILED }

    private final String taskId;
    private final String vehicleId;
    private final MobilityStatus mobilityStatus;
    private final int signalStrength;        // dBm, e.g. -30 to -90
    private final int criticalTask;          // 0 or 1
    private final double bandwidthMbps;
    private final int numberOfInstructions;  // in millions of instructions (MI)
    private final double taskSizeMB;

    // Set after ML prediction
    private volatile boolean isOffloaded;
    private volatile String offloadTarget;   // "cloud", "rsu", "vehicle"

    // Runtime state
    private final AtomicReference<TaskState> state;
    private volatile ComputeNode assignedNode;
    private volatile int allocatedMips;
    private volatile int allocatedRamMB;

    // Timing
    private volatile long creationTimeMs;
    private volatile long assignmentTimeMs;
    private volatile long completionTimeMs;
    private volatile double simulatedExecTimeMs; // computed execution time

    public Task(String taskId, String vehicleId, MobilityStatus mobilityStatus,
                int signalStrength, int criticalTask, double bandwidthMbps,
                int numberOfInstructions, double taskSizeMB) {
        this.taskId = taskId;
        this.vehicleId = vehicleId;
        this.mobilityStatus = mobilityStatus;
        this.signalStrength = signalStrength;
        this.criticalTask = criticalTask;
        this.bandwidthMbps = bandwidthMbps;
        this.numberOfInstructions = numberOfInstructions;
        this.taskSizeMB = taskSizeMB;
        this.state = new AtomicReference<>(TaskState.CREATED);
        this.creationTimeMs = System.currentTimeMillis();
    }

    // --- Getters ---
    public String getTaskId() { return taskId; }
    public String getVehicleId() { return vehicleId; }
    public MobilityStatus getMobilityStatus() { return mobilityStatus; }
    public int getSignalStrength() { return signalStrength; }
    public int getCriticalTask() { return criticalTask; }
    public double getBandwidthMbps() { return bandwidthMbps; }
    public int getNumberOfInstructions() { return numberOfInstructions; }
    public double getTaskSizeMB() { return taskSizeMB; }
    public boolean isOffloaded() { return isOffloaded; }
    public String getOffloadTarget() { return offloadTarget; }
    public TaskState getState() { return state.get(); }
    public ComputeNode getAssignedNode() { return assignedNode; }
    public int getAllocatedMips() { return allocatedMips; }
    public int getAllocatedRamMB() { return allocatedRamMB; }
    public long getCreationTimeMs() { return creationTimeMs; }
    public long getAssignmentTimeMs() { return assignmentTimeMs; }
    public long getCompletionTimeMs() { return completionTimeMs; }
    public double getSimulatedExecTimeMs() { return simulatedExecTimeMs; }

    // --- Setters ---
    public void setOffloadDecision(boolean isOffloaded, String offloadTarget) {
        this.isOffloaded = isOffloaded;
        this.offloadTarget = offloadTarget;
    }

    public void setState(TaskState s) { this.state.set(s); }

    public void assignTo(ComputeNode node, int mips, int ramMB) {
        this.assignedNode = node;
        this.allocatedMips = mips;
        this.allocatedRamMB = ramMB;
        this.assignmentTimeMs = System.currentTimeMillis();
        this.state.set(TaskState.RUNNING);
    }

    public void setSimulatedExecTimeMs(double t) { this.simulatedExecTimeMs = t; }
    public void markCompleted() {
        this.completionTimeMs = System.currentTimeMillis();
        this.state.set(TaskState.COMPLETED);
    }

    /**
     * Compute simulated execution time:
     *
     *   T_exec = (numberOfInstructions / allocatedMips) * 1000  [ms]
     *   T_transfer = (taskSizeMB * 8) / bandwidthMbps           [ms]  (converted)
     *   T_prop = node.getPropagationDelayMs()
     *   T_total = T_exec + T_transfer + T_prop
     */
    public double computeSimulatedExecTimeMs() {
        if (assignedNode == null) return Double.MAX_VALUE;

        double tExec = ((double) numberOfInstructions / allocatedMips) * 1000.0;
        double tTransfer = (taskSizeMB * 8.0) / bandwidthMbps; // seconds, then *1000
        tTransfer = tTransfer * 1000.0;
        double tProp = assignedNode.getPropagationDelayMs();

        this.simulatedExecTimeMs = tExec + tTransfer + tProp;
        return this.simulatedExecTimeMs;
    }

    @Override
    public String toString() {
        return String.format("Task[%s | veh=%s | MI=%d | %.2f MB | %s | target=%s | state=%s]",
                taskId, vehicleId, numberOfInstructions, taskSizeMB,
                mobilityStatus, offloadTarget, state.get());
    }
}

